#ifndef PLATFORM_CFG_H
#define PLATFORM_CFG_H

#define CONTROL_OUT_IO_B 																	\
	(AT91C_PIO_PB16 | AT91C_PIO_PB17 | AT91C_PIO_PB18 | AT91C_PIO_PB30 | AT91C_PIO_PB31 )

#define CONTROL_OUT_IO_A 																	\
	(AT91C_PIO_PA9   )

#define	ASSERT_nRESET_PHY	\
		HAL_WRITE_UINT32( AT91C_PIOA_CODR , AT91C_PIO_PA9 )

#define DEASSERT_nRESET_PHY	\
		HAL_WRITE_UINT32( AT91C_PIOA_SODR , AT91C_PIO_PA9 )

#define	ASSERT_nRESET_PWR	\
	HAL_WRITE_UINT32( AT91C_PIOB_CODR , AT91C_PIO_PB16 )

#define	DEASSERT_nRESET_PWR	\
	HAL_WRITE_UINT32( AT91C_PIOB_SODR , AT91C_PIO_PB16 )

#define	ASSERT_nRESET_GPRS	\
	HAL_WRITE_UINT32( AT91C_PIOB_CODR , AT91C_PIO_PB17 )

#define	DEASSERT_nRESET_GPRS	\
	HAL_WRITE_UINT32( AT91C_PIOB_SODR , AT91C_PIO_PB17 )

#define	LED_P0_ON	\
	HAL_WRITE_UINT32( AT91C_PIOB_CODR , AT91C_PIO_PB18)

#define	LED_P0_OFF	\
	HAL_WRITE_UINT32( AT91C_PIOB_SODR , AT91C_PIO_PB18)

#define	LED_P1_ON	\
	HAL_WRITE_UINT32( AT91C_PIOB_CODR , AT91C_PIO_PB30)

#define	LED_P1_OFF	\
	HAL_WRITE_UINT32( AT91C_PIOB_SODR , AT91C_PIO_PB30)

#define	LED_P2_ON	\
	HAL_WRITE_UINT32( AT91C_PIOB_CODR , AT91C_PIO_PB31)

#define	LED_P2_OFF	\
	HAL_WRITE_UINT32( AT91C_PIOB_SODR , AT91C_PIO_PB31)

#endif // PLATFORM_CFG_H

